from arc.state import Resource

BASIC_RESOURCES: list[Resource] = [
    {
        "id": "r_metal_parts",
        "name": "Metal Parts",
        "category": "resource",
        "resource_type": "basic",
        "image": "/resources/r_metal_parts.png",
        "resources": [],
        "rarity": "Common",
        "stack_size": 50,
    },
    {
        "id": "r_rubber_parts",
        "name": "Rubber Parts",
        "category": "resource",
        "resource_type": "basic",
        "image": "/resources/r_rubber_parts.png",
        "resources": [],
        "rarity": "Common",
        "stack_size": 50,
    },
    {
        "id": "r_plastic_parts",
        "name": "Plastic Parts",
        "category": "resource",
        "resource_type": "basic",
        "image": "/resources/r_plastic_parts.png",
        "resources": [],
        "rarity": "Common",
        "stack_size": 50,
    },
    {
        "id": "r_fabric",
        "name": "Fabric",
        "category": "resource",
        "resource_type": "basic",
        "image": "/resources/r_fabric.png",
        "resources": [],
        "rarity": "Common",
        "stack_size": 50,
    },
    {
        "id": "r_chemicals",
        "name": "Chemicals",
        "category": "resource",
        "resource_type": "basic",
        "image": "/resources/r_chemicals.png",
        "resources": [],
        "rarity": "Common",
        "stack_size": 50,
    },
    {
        "id": "r_magnet",
        "name": "Magnet",
        "category": "resource",
        "resource_type": "basic",
        "image": "/resources/r_magnet.png",
        "resources": [],
        "rarity": "Uncommon",
        "stack_size": 15,
    },
    {
        "id": "r_steel_spring",
        "name": "Steel Spring",
        "category": "resource",
        "resource_type": "basic",
        "image": "/resources/r_steel_spring.png",
        "resources": [],
        "rarity": "Uncommon",
        "stack_size": 15,
    },
    {
        "id": "r_oil",
        "name": "Oil",
        "category": "resource",
        "resource_type": "basic",
        "image": "/resources/r_oil.png",
        "resources": [],
        "rarity": "Uncommon",
        "stack_size": 15,
    },
    {
        "id": "r_wires",
        "name": "Wires",
        "category": "resource",
        "resource_type": "basic",
        "image": "/resources/r_wires.png",
        "resources": [],
        "rarity": "Uncommon",
        "stack_size": 15,
    },
    {
        "id": "r_duct_tape",
        "name": "Duct Tape",
        "category": "resource",
        "resource_type": "basic",
        "image": "/resources/r_duct_tape.png",
        "resources": [],
        "rarity": "Uncommon",
        "stack_size": 15,
    },
    {
        "id": "r_arc_alloy",
        "name": "Arc Alloy",
        "category": "resource",
        "resource_type": "basic",
        "image": "/resources/r_arc_alloy.png",
        "resources": [],
        "rarity": "Uncommon",
        "stack_size": 15,
    },
    {
        "id": "r_battery",
        "name": "Battery",
        "category": "resource",
        "resource_type": "basic",
        "image": "/resources/r_battery.png",
        "resources": [],
        "rarity": "Uncommon",
        "stack_size": 15,
    },
    {
        "id": "r_simple_gun_parts",
        "name": "Simple Gun Parts",
        "category": "resource",
        "resource_type": "basic",
        "image": "/resources/r_simple_gun_parts.png",
        "resources": [],
        "rarity": "Uncommon",
        "stack_size": 10,
    },
]

REFINED_RESOURCES: list[Resource] = [
    {
        "id": "r_mechanical_components",
        "name": "Mechanical Components",
        "category": "resource",
        "resource_type": "refined",
        "image": "/resources/r_mechanical_components.png",
        "resources": [
            {"resource": "r_metal_parts", "quantity": 7},
            {"resource": "r_rubber_parts", "quantity": 3},
        ],
        "rarity": "Uncommon",
        "stack_size": 3,
    },
    {
        "id": "r_electrical_components",
        "name": "Electrical Components",
        "category": "resource",
        "resource_type": "refined",
        "image": "/resources/r_electrical_components.png",
        "resources": [
            {"resource": "r_plastic_parts", "quantity": 8},
            {"resource": "r_rubber_parts", "quantity": 4},
        ],
        "rarity": "Uncommon",
        "stack_size": 10,
    },
    {
        "id": "r_advanced_mechanical_components",
        "name": "Advanced Mechanical Components",
        "category": "resource",
        "resource_type": "refined",
        "image": "/resources/r_advanced_mechanical_components.png",
        "resources": [
            {"resource": "r_mechanical_components", "quantity": 2},
            {"resource": "r_steel_spring", "quantity": 2},
        ],
        "rarity": "Rare",
        "stack_size": 5,
    },
    {
        "id": "r_advanced_electrical_components",
        "name": "Advanced Electrical Components",
        "category": "resource",
        "resource_type": "refined",
        "image": "/resources/r_advanced_electrical_components.png",
        "resources": [
            {"resource": "r_electrical_components", "quantity": 2},
            {"resource": "r_wires", "quantity": 3},
        ],
        "rarity": "Rare",
        "stack_size": 5,
    },
    {
        "id": "r_light_gun_parts",
        "name": "Light Gun Parts",
        "category": "resource",
        "resource_type": "refined",
        "image": "/resources/r_light_gun_parts.png",
        "resources": [
            {"resource": "r_simple_gun_parts", "quantity": 4},
        ],
        "rarity": "Rare",
        "stack_size": 5,
    },
    {
        "id": "r_medium_gun_parts",
        "name": "Medium Gun Parts",
        "category": "resource",
        "resource_type": "refined",
        "image": "/resources/r_medium_gun_parts.png",
        "resources": [
            {"resource": "r_simple_gun_parts", "quantity": 4},
        ],
        "rarity": "Rare",
        "stack_size": 5,
    },
    {
        "id": "r_heavy_gun_parts",
        "name": "Heavy Gun Parts",
        "category": "resource",
        "resource_type": "refined",
        "image": "/resources/r_heavy_gun_parts.png",
        "resources": [
            {"resource": "r_simple_gun_parts", "quantity": 4},
        ],
        "rarity": "Rare",
        "stack_size": 5,
    },
]

RESOURCES: list[Resource] = BASIC_RESOURCES + REFINED_RESOURCES

# Create a mapping from resource ID to resource object for easy lookup
RESOURCE_BY_ID: dict[str, Resource] = {r["id"]: r for r in RESOURCES}

# Create a mapping from resource name to resource ID for migration
RESOURCE_NAME_TO_ID: dict[str, str] = {r["name"]: r["id"] for r in RESOURCES}

