from arc.state import Item

WEAPON_MODS: list[Item] = [
    {
        "id": "m_compensator_1",
        "name": "Compensator 1",
        "category": "Weapon Mod",
        "icon": "weapon-mod-1",
        "image": "/items/m_compensator_1.png",
        "symbol": "/symbols/s_muzzle.webp",
        "resources": [
            {"resource": "r_metal_parts", "quantity": 6},
            {"resource": "r_wire", "quantity": 1},
        ],
        "tier_resources": {},
        "rarity": "Common",
        "mod_type": "muzzle",
        "weapon_mod_slots": None,
        "backpack_slots": None,
        "safe_pocket_slots": None,
        "quick_use_slots": None,
        "max_shield": None,
        "stack_size": 1,
    },
    {
        "id": "m_muzzle_brake_1",
        "name": "Muzzle Brake 1",
        "category": "Weapon Mod",
        "icon": "weapon-mod-1",
        "image": "/items/m_muzzle_brake_1.png",
        "symbol": "/symbols/s_muzzle.webp",
        "resources": [
            {"resource": "r_metal_parts", "quantity": 6},
            {"resource": "r_wire", "quantity": 1},
        ],
        "tier_resources": {},
        "rarity": "Common",
        "mod_type": "muzzle",
        "weapon_mod_slots": None,
        "backpack_slots": None,
        "safe_pocket_slots": None,
        "quick_use_slots": None,
        "max_shield": None,
        "stack_size": 1,
    },
    {
        "id": "m_shotgun_choke_1",
        "name": "Shotgun Choke 1",
        "category": "Weapon Mod",
        "icon": "weapon-mod-1",
        "image": "/items/m_shotgun_choke_1.png",
        "symbol": "/symbols/s_shotgun_muzzle.webp",
        "resources": [
            {"resource": "r_metal_parts", "quantity": 6},
            {"resource": "r_wire", "quantity": 1},
        ],
        "tier_resources": {},
        "rarity": "Common",
        "mod_type": "shotgun_muzzle",
        "weapon_mod_slots": None,
        "backpack_slots": None,
        "safe_pocket_slots": None,
        "quick_use_slots": None,
        "max_shield": None,
        "stack_size": 1,
    },
    {
        "id": "m_angled_grip_1",
        "name": "Angled Grip 1",
        "category": "Weapon Mod",
        "icon": "weapon-mod-1",
        "image": "/items/m_angled_grip_1.png",
        "symbol": "/symbols/s_underbarrel.webp",
        "resources": [
            {"resource": "r_metal_parts", "quantity": 6},
            {"resource": "r_duct_tape", "quantity": 1},
        ],
        "tier_resources": {},
        "rarity": "Common",
        "mod_type": "underbarrel",
        "weapon_mod_slots": None,
        "backpack_slots": None,
        "safe_pocket_slots": None,
        "quick_use_slots": None,
        "max_shield": None,
        "stack_size": 1,
    },
    {
        "id": "m_vertical_grip_1",
        "name": "Vertical Grip 1",
        "category": "Weapon Mod",
        "icon": "weapon-mod-1",
        "image": "/items/m_vertical_grip_1.png",
        "symbol": "/symbols/s_underbarrel.webp",
        "resources": [
            {"resource": "r_metal_parts", "quantity": 6},
            {"resource": "r_duct_tape", "quantity": 1},
        ],
        "tier_resources": {},
        "rarity": "Common",
        "mod_type": "underbarrel",
        "weapon_mod_slots": None,
        "backpack_slots": None,
        "safe_pocket_slots": None,
        "quick_use_slots": None,
        "max_shield": None,
        "stack_size": 1,
    },
    {
        "id": "m_light_mag_1",
        "name": "Extended Light Mag 1",
        "category": "Weapon Mod",
        "icon": "weapon-mod-1",
        "image": "/items/m_light_mag_1.png",
        "symbol": "/symbols/s_light_mag.webp",
        "resources": [
            {"resource": "r_metal_parts", "quantity": 6},
            {"resource": "r_steel_spring", "quantity": 1},
        ],
        "tier_resources": {},
        "rarity": "Common",
        "mod_type": "light_mag",
        "weapon_mod_slots": None,
        "backpack_slots": None,
        "safe_pocket_slots": None,
        "quick_use_slots": None,
        "max_shield": None,
        "stack_size": 1,
    },
    {
        "id": "m_medium_mag_1",
        "name": "Extended Medium Mag 1",
        "category": "Weapon Mod",
        "icon": "weapon-mod-1",
        "image": "/items/m_medium_mag_1.png",
        "symbol": "/symbols/s_medium_mag.webp",
        "resources": [
            {"resource": "r_metal_parts", "quantity": 6},
            {"resource": "r_steel_spring", "quantity": 1},
        ],
        "tier_resources": {},
        "rarity": "Common",
        "mod_type": "medium_mag",
        "weapon_mod_slots": None,
        "backpack_slots": None,
        "safe_pocket_slots": None,
        "quick_use_slots": None,
        "max_shield": None,
        "stack_size": 1,
    },
    {
        "id": "m_shotgun_mag_1",
        "name": "Extended Shotgun Mag 1",
        "category": "Weapon Mod",
        "icon": "weapon-mod-1",
        "image": "/items/m_shotgun_mag_1.png",
        "symbol": "/symbols/s_shotgun_mag.webp",
        "resources": [
            {"resource": "r_metal_parts", "quantity": 6},
            {"resource": "r_steel_spring", "quantity": 1},
        ],
        "tier_resources": {},
        "rarity": "Common",
        "mod_type": "shotgun_mag",
        "weapon_mod_slots": None,
        "backpack_slots": None,
        "safe_pocket_slots": None,
        "quick_use_slots": None,
        "max_shield": None,
        "stack_size": 1,
    },
    {
        "id": "m_stock_1",
        "name": "Stable Stock 1",
        "category": "Weapon Mod",
        "icon": "weapon-mod-1",
        "image": "/items/m_stock_1.png",
        "symbol": "/symbols/s_stock.webp",
        "resources": [
            {"resource": "r_rubber_parts", "quantity": 7},
            {"resource": "r_duct_tape", "quantity": 1},
        ],
        "tier_resources": {},
        "rarity": "Common",
        "mod_type": "stock",
        "weapon_mod_slots": None,
        "backpack_slots": None,
        "safe_pocket_slots": None,
        "quick_use_slots": None,
        "max_shield": None,
        "stack_size": 1,
    },
]